"""baseline schema

Revision ID: 08d70a149300
Revises: 
Create Date: 2026-07-19 20:25:18.308777

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08d70a149300'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_policies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('policy_family_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('resource_selector_json', sa.Text(), nullable=False),
    sa.Column('dsl_conditions_json', sa.Text(), nullable=False),
    sa.Column('action_selector', sa.String(length=120), nullable=False),
    sa.Column('approver_subject_ids_json', sa.Text(), nullable=False),
    sa.Column('approver_mode', sa.String(length=20), nullable=False),
    sa.Column('require_mfa_for_requester', sa.Boolean(), nullable=False),
    sa.Column('require_mfa_for_approver', sa.Boolean(), nullable=False),
    sa.Column('max_grant_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('allow_self_approval', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_policies_is_active'), 'approval_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_approval_policies_policy_family_id'), 'approval_policies', ['policy_family_id'], unique=False)
    op.create_index(op.f('ix_approval_policies_tenant_id'), 'approval_policies', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('trusted_ssh_ca_id', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('credential', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_assets_trusted_ssh_ca_id'), 'assets', ['trusted_ssh_ca_id'], unique=False)
    op.create_table('automation_job_runs',
    sa.Column('message_id', sa.String(length=120), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('playbook_name', sa.String(length=128), nullable=True),
    sa.Column('check_mode', sa.Boolean(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_automation_job_runs_job_type'), 'automation_job_runs', ['job_type'], unique=False)
    op.create_index(op.f('ix_automation_job_runs_status'), 'automation_job_runs', ['status'], unique=False)
    op.create_index(op.f('ix_automation_job_runs_tenant_id'), 'automation_job_runs', ['tenant_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('public_key_fingerprint', sa.String(length=160), nullable=False),
    sa.Column('previous_public_key_fingerprint', sa.String(length=160), nullable=True),
    sa.Column('mtls_certificate_fingerprint', sa.String(length=160), nullable=True),
    sa.Column('attestation_nonce', sa.String(length=160), nullable=True),
    sa.Column('attestation_digest', sa.String(length=160), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_connectors_tenant_name')
    )
    op.create_index(op.f('ix_connectors_tenant_id'), 'connectors', ['tenant_id'], unique=False)
    op.create_table('jit_grants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_request_id', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_session_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('constraints_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jit_grants_asset_id'), 'jit_grants', ['asset_id'], unique=False)
    op.create_index(op.f('ix_jit_grants_subject_id'), 'jit_grants', ['subject_id'], unique=False)
    op.create_index(op.f('ix_jit_grants_tenant_id'), 'jit_grants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_jit_grants_workflow_request_id'), 'jit_grants', ['workflow_request_id'], unique=False)
    op.create_table('license_configurations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('configured_edition', sa.String(length=32), nullable=False),
    sa.Column('license_verifier', sa.String(length=32), nullable=False),
    sa.Column('license_key', sa.Text(), nullable=False),
    sa.Column('license_signing_secret', sa.Text(), nullable=False),
    sa.Column('license_public_key', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('notification_rule_id', sa.Integer(), nullable=False),
    sa.Column('webhook_endpoint_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_deliveries_event_type'), 'notification_deliveries', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_notification_rule_id'), 'notification_deliveries', ['notification_rule_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_status'), 'notification_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_tenant_id'), 'notification_deliveries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_webhook_endpoint_id'), 'notification_deliveries', ['webhook_endpoint_id'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('event_types_json', sa.Text(), nullable=False),
    sa.Column('webhook_endpoint_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_notification_rules_tenant_name')
    )
    op.create_index(op.f('ix_notification_rules_tenant_id'), 'notification_rules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_webhook_endpoint_id'), 'notification_rules', ['webhook_endpoint_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_organizations_tenant_name')
    )
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('protocols', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('secret_records',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('nonce', sa.String(length=120), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('encrypted_data_key', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_records_status'), 'secret_records', ['status'], unique=False)
    op.create_table('session_recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.String(length=120), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_uri', sa.String(length=512), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_recordings_account_id'), 'session_recordings', ['account_id'], unique=False)
    op.create_index(op.f('ix_session_recordings_asset_id'), 'session_recordings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_session_recordings_session_id'), 'session_recordings', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_recordings_subject_id'), 'session_recordings', ['subject_id'], unique=False)
    op.create_index(op.f('ix_session_recordings_tenant_id'), 'session_recordings', ['tenant_id'], unique=False)
    op.create_table('ssh_certificate_authorities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key_secret_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validity_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_ssh_certificate_authorities_tenant_name')
    )
    op.create_index(op.f('ix_ssh_certificate_authorities_tenant_id'), 'ssh_certificate_authorities', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('totp_secret', sa.String(length=200), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_project_id'), 'users', ['project_id'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('event_types_json', sa.Text(), nullable=False),
    sa.Column('signing_secret_digest', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_webhook_endpoints_tenant_name')
    )
    op.create_index(op.f('ix_webhook_endpoints_tenant_id'), 'webhook_endpoints', ['tenant_id'], unique=False)
    op.create_table('workflow_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('requester_id', sa.String(length=64), nullable=False),
    sa.Column('requester_username', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('approver_id', sa.String(length=64), nullable=False),
    sa.Column('approver_username', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_requests_asset_id'), 'workflow_requests', ['asset_id'], unique=False)
    op.create_index(op.f('ix_workflow_requests_requester_id'), 'workflow_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_workflow_requests_tenant_id'), 'workflow_requests', ['tenant_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('secret_id', sa.String(length=120), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rotation_policy', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'asset_id', 'username', 'protocol', name='uq_accounts_asset_user_protocol')
    )
    op.create_index(op.f('ix_accounts_asset_id'), 'accounts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_accounts_organization_id'), 'accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_accounts_project_id'), 'accounts', ['project_id'], unique=False)
    op.create_index(op.f('ix_accounts_team_id'), 'accounts', ['team_id'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_id', sa.String(length=36), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_table('session_command_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output_excerpt', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['session_recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_command_events_recording_id'), 'session_command_events', ['recording_id'], unique=False)
    op.create_index(op.f('ix_session_command_events_session_id'), 'session_command_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_command_events_tenant_id'), 'session_command_events', ['tenant_id'], unique=False)
    op.create_index('ix_session_command_events_tenant_occurred_id', 'session_command_events', ['tenant_id', 'occurred_at', 'id'], unique=False)
    # 全文检索 GIN 表达式索引仅 PostgreSQL 支持（模型侧 ddl_if(dialect="postgresql")）；
    # autogenerate 无法反射表达式索引，此处手工补回并按方言守卫。
    if op.get_bind().dialect.name == 'postgresql':
        op.create_index(
            'ix_session_command_events_search_vector',
            'session_command_events',
            [sa.text("to_tsvector('simple', command || ' ' || output_excerpt)")],
            unique=False,
            postgresql_using='gin',
        )
    op.create_table('teams',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'organization_id', 'name', name='uq_teams_org_name')
    )
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_index(op.f('ix_teams_tenant_id'), 'teams', ['tenant_id'], unique=False)
    op.create_table('credential_rotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=240), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_secret_id', sa.String(length=120), nullable=True),
    sa.Column('new_secret_id', sa.String(length=120), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_rotations_account_id'), 'credential_rotations', ['account_id'], unique=False)
    op.create_index(op.f('ix_credential_rotations_tenant_id'), 'credential_rotations', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'organization_id', 'name', name='uq_projects_org_name')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('ssh_certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.String(length=120), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('serial', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('certificate_body', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('valid_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['ca_id'], ['ssh_certificate_authorities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'serial', name='uq_ssh_certificates_tenant_serial')
    )
    op.create_index(op.f('ix_ssh_certificates_account_id'), 'ssh_certificates', ['account_id'], unique=False)
    op.create_index(op.f('ix_ssh_certificates_asset_id'), 'ssh_certificates', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ssh_certificates_ca_id'), 'ssh_certificates', ['ca_id'], unique=False)
    op.create_index(op.f('ix_ssh_certificates_tenant_id'), 'ssh_certificates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssh_certificates_tenant_id'), table_name='ssh_certificates')
    op.drop_index(op.f('ix_ssh_certificates_ca_id'), table_name='ssh_certificates')
    op.drop_index(op.f('ix_ssh_certificates_asset_id'), table_name='ssh_certificates')
    op.drop_index(op.f('ix_ssh_certificates_account_id'), table_name='ssh_certificates')
    op.drop_table('ssh_certificates')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_credential_rotations_tenant_id'), table_name='credential_rotations')
    op.drop_index(op.f('ix_credential_rotations_account_id'), table_name='credential_rotations')
    op.drop_table('credential_rotations')
    op.drop_index(op.f('ix_teams_tenant_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_table('teams')
    if op.get_bind().dialect.name == 'postgresql':
        op.drop_index('ix_session_command_events_search_vector', table_name='session_command_events')
    op.drop_index('ix_session_command_events_tenant_occurred_id', table_name='session_command_events')
    op.drop_index(op.f('ix_session_command_events_tenant_id'), table_name='session_command_events')
    op.drop_index(op.f('ix_session_command_events_session_id'), table_name='session_command_events')
    op.drop_index(op.f('ix_session_command_events_recording_id'), table_name='session_command_events')
    op.drop_table('session_command_events')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_team_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_project_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_organization_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_asset_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_workflow_requests_tenant_id'), table_name='workflow_requests')
    op.drop_index(op.f('ix_workflow_requests_requester_id'), table_name='workflow_requests')
    op.drop_index(op.f('ix_workflow_requests_asset_id'), table_name='workflow_requests')
    op.drop_table('workflow_requests')
    op.drop_index(op.f('ix_webhook_endpoints_tenant_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_project_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ssh_certificate_authorities_tenant_id'), table_name='ssh_certificate_authorities')
    op.drop_table('ssh_certificate_authorities')
    op.drop_index(op.f('ix_session_recordings_tenant_id'), table_name='session_recordings')
    op.drop_index(op.f('ix_session_recordings_subject_id'), table_name='session_recordings')
    op.drop_index(op.f('ix_session_recordings_session_id'), table_name='session_recordings')
    op.drop_index(op.f('ix_session_recordings_asset_id'), table_name='session_recordings')
    op.drop_index(op.f('ix_session_recordings_account_id'), table_name='session_recordings')
    op.drop_table('session_recordings')
    op.drop_index(op.f('ix_secret_records_status'), table_name='secret_records')
    op.drop_table('secret_records')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notification_rules_webhook_endpoint_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_tenant_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_notification_deliveries_webhook_endpoint_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_tenant_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_status'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_notification_rule_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_event_type'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_table('license_configurations')
    op.drop_index(op.f('ix_jit_grants_workflow_request_id'), table_name='jit_grants')
    op.drop_index(op.f('ix_jit_grants_tenant_id'), table_name='jit_grants')
    op.drop_index(op.f('ix_jit_grants_subject_id'), table_name='jit_grants')
    op.drop_index(op.f('ix_jit_grants_asset_id'), table_name='jit_grants')
    op.drop_table('jit_grants')
    op.drop_index(op.f('ix_connectors_tenant_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_automation_job_runs_tenant_id'), table_name='automation_job_runs')
    op.drop_index(op.f('ix_automation_job_runs_status'), table_name='automation_job_runs')
    op.drop_index(op.f('ix_automation_job_runs_job_type'), table_name='automation_job_runs')
    op.drop_table('automation_job_runs')
    op.drop_index(op.f('ix_assets_trusted_ssh_ca_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_approval_policies_tenant_id'), table_name='approval_policies')
    op.drop_index(op.f('ix_approval_policies_policy_family_id'), table_name='approval_policies')
    op.drop_index(op.f('ix_approval_policies_is_active'), table_name='approval_policies')
    op.drop_table('approval_policies')
    # ### end Alembic commands ###
