"""add data masking rule

Revision ID: 4eb764da4aab
Revises: b75f09654bda
Create Date: 2026-07-24 23:58:03.072640

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4eb764da4aab'
down_revision: str | None = 'b75f09654bda'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_masking_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('patterns_json', sa.Text(), nullable=False),
    sa.Column('mask_method', sa.String(length=16), nullable=False),
    sa.Column('keep_prefix', sa.Integer(), nullable=False),
    sa.Column('keep_suffix', sa.Integer(), nullable=False),
    sa.Column('placeholder', sa.String(length=32), nullable=False),
    sa.Column('subject_ids_json', sa.Text(), nullable=False),
    sa.Column('asset_ids_json', sa.Text(), nullable=False),
    sa.Column('account_ids_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_masking_rules_tenant_id'), 'data_masking_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_masking_rules_tenant_id'), table_name='data_masking_rules')
    op.drop_table('data_masking_rules')
    # ### end Alembic commands ###
