"""add command filter acl

Revision ID: b75f09654bda
Revises: 4b6380add4e5
Create Date: 2026-07-24 23:46:45.693698

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b75f09654bda'
down_revision: str | None = '4b6380add4e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_filter_acls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reviewer_subject_ids_json', sa.Text(), nullable=False),
    sa.Column('subject_ids_json', sa.Text(), nullable=False),
    sa.Column('asset_ids_json', sa.Text(), nullable=False),
    sa.Column('account_ids_json', sa.Text(), nullable=False),
    sa.Column('command_group_ids_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_filter_acls_tenant_id'), 'command_filter_acls', ['tenant_id'], unique=False)
    op.create_table('command_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('patterns_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_groups_tenant_id'), 'command_groups', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_groups_tenant_id'), table_name='command_groups')
    op.drop_table('command_groups')
    op.drop_index(op.f('ix_command_filter_acls_tenant_id'), table_name='command_filter_acls')
    op.drop_table('command_filter_acls')
    # ### end Alembic commands ###
