"""add sessions

Revision ID: 4b6380add4e5
Revises: db1145a807fc
Create Date: 2026-07-24 21:47:46.146525

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b6380add4e5'
down_revision: str | None = 'db1145a807fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.String(length=120), nullable=False),
    sa.Column('connector_id', sa.String(length=120), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('connection_token_id', sa.String(length=128), nullable=False),
    sa.Column('connector_session_id', sa.String(length=120), nullable=False),
    sa.Column('connection_url', sa.String(length=512), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=False),
    sa.Column('client_ip_source', sa.String(length=64), nullable=False),
    sa.Column('workflow_request_id', sa.String(length=64), nullable=False),
    sa.Column('jit_grant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('audit_event_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_jit_grant_id'), 'sessions', ['jit_grant_id'], unique=False)
    op.create_index('ix_sessions_tenant_subject_created', 'sessions', ['tenant_id', 'subject_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_tenant_subject_created', table_name='sessions')
    op.drop_index(op.f('ix_sessions_jit_grant_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
